# Generated by Django 2.2 on 2019-04-23 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html', models.TextField()),
                ('parse_status', models.CharField(default='unknow', max_length=64, verbose_name='解析状态')),
                ('is_valid', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.CharField(blank=True, max_length=128, null=True, verbose_name='错误类型')),
                ('info', models.TextField(blank=True, null=True, verbose_name='信息')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '爬虫记录',
                'verbose_name_plural': '爬虫记录',
            },
        ),
        migrations.CreateModel(
            name='UpdateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='代码')),
                ('html', models.TextField()),
                ('update_data', jsonfield.fields.JSONField(verbose_name='记录新旧数据')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '更新记录',
                'verbose_name_plural': '更新记录',
            },
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(verbose_name='发送的数据包')),
                ('response', jsonfield.fields.JSONField(verbose_name='返回的数据包')),
                ('type', models.CharField(default='xcx', max_length=64, verbose_name='消息类型')),
                ('template_id', models.CharField(max_length=64, verbose_name='模板id')),
                ('status', models.CharField(default='ok', max_length=64, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '消息通知记录',
                'verbose_name_plural': '消息通知记录',
            },
        ),
        migrations.CreateModel(
            name='BrowseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('info', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='用户数据')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
            },
        ),
    ]
