# Generated by Django 2.2 on 2019-04-23 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='牌子')),
                ('en_name', models.CharField(db_index=True, max_length=128, verbose_name='英文名')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='图标')),
                ('domain', models.CharField(blank=True, max_length=256, null=True, verbose_name='官网')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ('order', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分类名')),
                ('href', models.CharField(blank=True, max_length=256, null=True, verbose_name='链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ('order', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='商品名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='female', max_length=64, verbose_name='性别')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='商品号')),
                ('group_code', models.CharField(db_index=True, max_length=64, verbose_name='商品分类')),
                ('source_url', models.CharField(max_length=256, verbose_name='源url')),
                ('html', models.TextField()),
                ('white_price', models.FloatField(default=0, max_length=64, verbose_name='原价')),
                ('price', models.FloatField(default=0, max_length=64, verbose_name='实际价格')),
                ('raw_products', jsonfield.fields.JSONField(verbose_name='相关产品原始数据')),
                ('other_style', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='其他款式数据')),
                ('img_urls', jsonfield.fields.JSONField()),
                ('size_select', jsonfield.fields.JSONField()),
                ('size_valid', jsonfield.fields.JSONField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('detail', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='细节')),
                ('delivery', models.TextField(blank=True, null=True, verbose_name='配送信息')),
                ('read_count', models.IntegerField(default=0, verbose_name='查看数量')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Brand', verbose_name='品牌')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('order', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标签名')),
                ('href', models.CharField(blank=True, max_length=256, null=True, verbose_name='链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'ordering': ('order', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='ProductMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_type', models.CharField(choices=[('new', '新品'), ('down', '降价'), ('recommend', '推荐')], max_length=64, verbose_name='标记类型')),
                ('price', models.FloatField(db_index=True, verbose_name='价格')),
                ('change', models.FloatField(blank=True, db_index=True, null=True, verbose_name='价格变化')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品标记',
                'verbose_name_plural': '产品标记',
                'ordering': ['order', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.Tag', verbose_name='标签'),
        ),
    ]
