# Generated by Django 2.1.8 on 2019-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmark',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
